# Generated by Django 2.0.6 on 2018-06-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('dataNasc', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=11)),
                ('profissoes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Concursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao', models.CharField(max_length=50)),
                ('edital', models.CharField(max_length=7)),
                ('codigoConcurso', models.CharField(max_length=50)),
                ('vagas', models.TextField()),
            ],
        ),
    ]
