-- MySQL Script generated by MySQL Workbench
-- Sat Jun  9 13:53:51 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema esPalmaMao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema esPalmaMao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `esPalmaMao` DEFAULT CHARACTER SET utf8 ;
USE `esPalmaMao` ;

-- -----------------------------------------------------
-- Table `esPalmaMao`.`candidatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esPalmaMao`.`candidatos` (
  `idcandidatos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `dataNasc` DATE NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcandidatos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esPalmaMao`.`profCandidatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esPalmaMao`.`profCandidatos` (
  `idprofCandidatos` INT NOT NULL AUTO_INCREMENT,
  `nomeprofissoes` VARCHAR(255) NOT NULL,
  `candidatos_idcandidatos` INT NOT NULL,
  PRIMARY KEY (`idprofCandidatos`),
  INDEX `fk_profCandidatos_candidatos_idx` (`candidatos_idcandidatos` ASC),
  CONSTRAINT `fk_profCandidatos_candidatos`
    FOREIGN KEY (`candidatos_idcandidatos`)
    REFERENCES `esPalmaMao`.`candidatos` (`idcandidatos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esPalmaMao`.`concursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esPalmaMao`.`concursos` (
  `idconcursos` INT NOT NULL AUTO_INCREMENT,
  `orgao` VARCHAR(45) NOT NULL,
  `edital` VARCHAR(45) NOT NULL,
  `codConcurso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idconcursos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esPalmaMao`.`profConcursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esPalmaMao`.`profConcursos` (
  `idprofConcursos` INT NOT NULL AUTO_INCREMENT,
  `nomeProfissoes` VARCHAR(255) NOT NULL,
  `concursos_idconcursos` INT NOT NULL,
  PRIMARY KEY (`idprofConcursos`),
  INDEX `fk_profConcursos_concursos1_idx` (`concursos_idconcursos` ASC),
  CONSTRAINT `fk_profConcursos_concursos1`
    FOREIGN KEY (`concursos_idconcursos`)
    REFERENCES `esPalmaMao`.`concursos` (`idconcursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
