# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-01 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edital', models.CharField(max_length=10)),
                ('codigo_curso', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='concurso',
            name='orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programa.Orgao'),
        ),
        migrations.AddField(
            model_name='concurso',
            name='vagas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programa.Profissao'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='profissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programa.Profissao'),
        ),
    ]
