//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace avaliacao_prodest.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    /// <summary>
    /// O namespace <see cref="avaliacao_prodest.Database"></see>
    /// Contém as classes que representam as tabelas do bando de dados
    /// </summary>
    public partial class AvaliacaoProdestDbEntities : DbContext
    {
        public AvaliacaoProdestDbEntities()
            : base("name=AvaliacaoProdestDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidatos> Candidatos { get; set; }
        public virtual DbSet<ProfissaoCandidato> ProfissaoCandidato { get; set; }
        public virtual DbSet<Concursos> Concursos { get; set; }
        public virtual DbSet<VagaConcurso> VagaConcurso { get; set; }
    }
}
