//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace avaliacao_prodest.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concursos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Concursos()
        {
            this.VagaConcurso = new HashSet<VagaConcurso>();
        }
    
        public string Orgao { get; set; }
        public string Edital { get; set; }
        public string Codigo { get; set; }
        public string IdConcurso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VagaConcurso> VagaConcurso { get; set; }
    }
}
